/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as FaucetRouteImport } from './routes/faucet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradeSymbolRouteImport } from './routes/trade.$symbol'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const FaucetRoute = FaucetRouteImport.update({
  id: '/faucet',
  path: '/faucet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeSymbolRoute = TradeSymbolRouteImport.update({
  id: '/trade/$symbol',
  path: '/trade/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faucet': typeof FaucetRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/vault': typeof VaultRoute
  '/trade/$symbol': typeof TradeSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faucet': typeof FaucetRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/vault': typeof VaultRoute
  '/trade/$symbol': typeof TradeSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faucet': typeof FaucetRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/vault': typeof VaultRoute
  '/trade/$symbol': typeof TradeSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faucet'
    | '/markets'
    | '/portfolio'
    | '/vault'
    | '/trade/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/faucet' | '/markets' | '/portfolio' | '/vault' | '/trade/$symbol'
  id:
    | '__root__'
    | '/'
    | '/faucet'
    | '/markets'
    | '/portfolio'
    | '/vault'
    | '/trade/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaucetRoute: typeof FaucetRoute
  MarketsRoute: typeof MarketsRoute
  PortfolioRoute: typeof PortfolioRoute
  VaultRoute: typeof VaultRoute
  TradeSymbolRoute: typeof TradeSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faucet': {
      id: '/faucet'
      path: '/faucet'
      fullPath: '/faucet'
      preLoaderRoute: typeof FaucetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$symbol': {
      id: '/trade/$symbol'
      path: '/trade/$symbol'
      fullPath: '/trade/$symbol'
      preLoaderRoute: typeof TradeSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaucetRoute: FaucetRoute,
  MarketsRoute: MarketsRoute,
  PortfolioRoute: PortfolioRoute,
  VaultRoute: VaultRoute,
  TradeSymbolRoute: TradeSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
