#!/usr/bin/env bash
# deploy-local.sh — Build, deploy, and initialize all contracts on the local Stellar network.
# Writes contract addresses to .env.local for the indexer/keepers.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WASM_DIR="$ROOT/target/wasm32v1-none/release"
ENV_FILE="$ROOT/.env.local"

RPC_URL="${RPC_URL:-http://localhost:8000/soroban/rpc}"
NETWORK_PASSPHRASE="${NETWORK_PASSPHRASE:-Standalone Network ; February 2017}"

# Stellar CLI identity — create an ephemeral 'admin' key if missing
if ! stellar keys address admin &>/dev/null; then
  echo "Creating 'admin' identity..."
  stellar keys generate admin --network local --fund
fi
ADMIN_ADDR=$(stellar keys address admin)
echo "Admin: $ADMIN_ADDR"

# Fund admin on local network (idempotent — ignores error if already funded)
stellar keys fund admin --network local 2>/dev/null || true

# ---------- Build ----------
echo ""
echo "=== Building WASMs ==="
(cd "$ROOT" && make build)

# ---------- Helper ----------
deploy() {
  local name=$1
  local wasm="$WASM_DIR/$(echo "$name" | tr '-' '_').wasm"
  echo "Deploying $name..."
  stellar contract deploy \
    --wasm "$wasm" \
    --source admin \
    --rpc-url "$RPC_URL" \
    --network-passphrase "$NETWORK_PASSPHRASE"
}

invoke() {
  stellar contract invoke \
    --source admin \
    --rpc-url "$RPC_URL" \
    --network-passphrase "$NETWORK_PASSPHRASE" \
    "$@"
}

# ---------- Deploy contracts ----------
echo ""
echo "=== Deploying contracts ==="

CM_ID=$(deploy config-manager)
echo "  config-manager : $CM_ID"

OR_ID=$(deploy oracle-router)
echo "  oracle-router  : $OR_ID"

ORACLE_ID=$(deploy oracle)
echo "  oracle (mock)  : $ORACLE_ID"

MOCK_TOKEN_ID=$(deploy mock-token)
echo "  mock-token     : $MOCK_TOKEN_ID"

VAULT_ID=$(deploy vault)
echo "  vault          : $VAULT_ID"

PM_ID=$(deploy position-manager)
echo "  position-mgr   : $PM_ID"

# ---------- Initialize contracts ----------
echo ""
echo "=== Initializing contracts ==="

echo "  config-manager.initialize(admin)"
invoke --id "$CM_ID" -- initialize \
  --admin_address "$ADMIN_ADDR"

echo "  oracle-router.initialize(config_manager)"
invoke --id "$OR_ID" -- initialize \
  --config_manager_address "$CM_ID"

echo "  oracle.initialize(config_manager)"
invoke --id "$ORACLE_ID" -- initialize \
  --config_manager "$CM_ID"

echo "  mock-token.initialize(admin, 7, USDC, USDC)"
invoke --id "$MOCK_TOKEN_ID" -- initialize \
  --_admin "$ADMIN_ADDR" \
  --decimals 7 \
  --name "USDC" \
  --symbol "USDC"

echo "  vault.initialize(admin, usdc, config_manager, position_manager)"
invoke --id "$VAULT_ID" -- initialize \
  --admin "$ADMIN_ADDR" \
  --asset "$MOCK_TOKEN_ID" \
  --config_manager "$CM_ID" \
  --position_manager "$PM_ID"

echo "  position-manager.initialize(admin, vault, config_manager, oracle_router)"
invoke --id "$PM_ID" -- initialize \
  --admin "$ADMIN_ADDR" \
  --vault_address "$VAULT_ID" \
  --config_manager "$CM_ID" \
  --oracle_router "$OR_ID"

# ---------- Grant roles ----------
echo ""
echo "=== Granting roles ==="

echo "  grant KEEPER to admin"
invoke --id "$CM_ID" -- grant_role \
  --caller "$ADMIN_ADDR" \
  --role KEEPER \
  --account "$ADMIN_ADDR"

echo "  grant PAUSER to admin"
invoke --id "$CM_ID" -- grant_role \
  --caller "$ADMIN_ADDR" \
  --role PAUSER \
  --account "$ADMIN_ADDR"

# ---------- Wire oracle ----------
echo ""
echo "=== Configuring oracle ==="

echo "  set oracle sources: BTCUSD → mock-oracle"
invoke --id "$OR_ID" -- set_oracle_sources \
  --caller "$ADMIN_ADDR" \
  --symbol BTCUSD \
  --primary '["'"$ORACLE_ID"'"]' \
  --secondary '[]'

echo "  set oracle sources: ETHUSD → mock-oracle"
invoke --id "$OR_ID" -- set_oracle_sources \
  --caller "$ADMIN_ADDR" \
  --symbol ETHUSD \
  --primary '["'"$ORACLE_ID"'"]' \
  --secondary '[]'

echo "  set oracle config"
invoke --id "$OR_ID" -- set_oracle_config \
  --caller "$ADMIN_ADDR" \
  --config '{"staleness_threshold":600,"max_deviation_bps":500,"cache_duration":60}'

# ---------- Seed oracle prices ----------
echo ""
echo "=== Seeding oracle prices ==="

echo "  BTC = 650000000000 (65,000 * 1e7)"
invoke --id "$ORACLE_ID" -- set_price \
  --caller "$ADMIN_ADDR" \
  --symbol BTCUSD \
  --price 650000000000

echo "  ETH = 35000000000 (3,500 * 1e7)"
invoke --id "$ORACLE_ID" -- set_price \
  --caller "$ADMIN_ADDR" \
  --symbol ETHUSD \
  --price 35000000000

# ---------- Write .env.local ----------
echo ""
echo "=== Writing $ENV_FILE ==="
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/deploy-local.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
DATABASE_URL=postgresql://stellars:stellars@localhost:5432/stellars
RPC_URL=$RPC_URL
NETWORK=testnet
START_LEDGER=0
POLL_INTERVAL_MS=3000
HEALTH_PORT=3001

# Contract addresses
VAULT_CONTRACT=$VAULT_ID
PM_CONTRACT=$PM_ID
CM_CONTRACT=$CM_ID
OR_CONTRACT=$OR_ID

# Extras (not consumed by indexer, useful for scripts)
ORACLE_CONTRACT=$ORACLE_ID
MOCK_TOKEN_CONTRACT=$MOCK_TOKEN_ID
ADMIN_ADDRESS=$ADMIN_ADDR
EOF

echo ""
echo "=== Done ==="
echo "Contracts deployed and initialized. Addresses in $ENV_FILE"
echo ""
echo "Next steps:"
echo "  1. Push DB schema:   pnpm --filter @stellars/db push"
echo "  2. Start indexer:    pnpm --filter @stellars/indexer dev"
echo "  3. Run smoke test:   bash scripts/smoke-test.sh"
